# Generated by Django 5.2 on 2025-05-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_type_service_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_payment',
            field=models.CharField(choices=[('0', 'Картой'), ('1', 'Наличные')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='uslugi',
            field=models.CharField(choices=[('1', 'В работе'), ('3', 'Отмена'), ('2', 'Выполнена'), ('0', 'Новая')], default='0', max_length=1),
        ),
    ]
